enum TimeZone {
    Pacific
    Mountain
    Central
    Eastern
    Atlantic
    Newfoundland
}

type Author {
    name: String
    timeZone: TimeZone
}

input AuthorInput {
    name: String
    timeZone: TimeZone
}
